# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
      before_deploy:
        - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis_pre_deploy -O travis_pre_deploy
        - chmod u+x ./travis_pre_deploy
        - ./travis_pre_deploy
      deploy:
        provider: releases
        skip_cleanup: true
        name: "Continuous build"
        body: "Continuous build ${TRAVIS_COMMIT} (${TRAVIS_JOB_WEB_URL})"
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: artifacts/*AppImage
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
      before_deploy:
        - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis_pre_deploy -O travis_pre_deploy
        - chmod u+x ./travis_pre_deploy
        - ./travis_pre_deploy
      deploy:
        provider: releases
        skip_cleanup: true
        name: "Continuous build"
        body: "Continuous build ${TRAVIS_COMMIT} (${TRAVIS_JOB_WEB_URL})"
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: artifacts/*dmg

# Branch Safelist (allow only master and version-tagged branches)
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
