# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis_deploy -O travis_deploy
          - chmod u+x ./travis_deploy
          - ./travis_pre_deploy -n "Release ${TRAVIS_TAG}" -b "Release" artifacts/*AppImage
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis_deploy -O travis_deploy
          - chmod u+x ./travis_deploy
          - ./travis_pre_deploy -n "Release ${TRAVIS_TAG}" -b "Release" artifacts/*dmg

# Branch Safelist (allow only master and version-tagged branches)
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
