# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        files:
          - src/ac
    - stage: System Tests
      name: Linux
      os: linux
      script: echo "Hello!" && src/ac "4+5"
