# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
      deploy:
        provider: releases
        api_key:
          secure: HZQ/M926XJHnhjA+r9PbLtgSE8ZYsxJ7oEA/6xxBZiK5WpCsFSYV3m2Sd1UGtkiFa6eawdwdI+0U2P0UBe/B1S17Y2euR/kGLbUa6C6PDiMlRLxVQLGWAIpYh8/k+8KA0ZcQbTv9gOkVfsz/ZFNZZRuwFKTVwPDXxORjX43ghVOSpfaOSqxFbDOtn+q1ywLF385j9mzy65KS1BcZCz96atpuJzcl7gDFT0PNrXbPIHqj46HXQbpb17/0hkZ3XwR9Q2cp577RmrJfOxw0Ac9CQrLE7Y9Qz8y4qOd42f1WR3T14PwfJl9MzEc14SHgpTxDf4LsHZSKtcAOdKoQ9p4c6InQO29C/23tEVeiw/c+BQeL71HCJ/BbQUn3WbRgWMj1TagJRV8iZpV6+D+VTbwVJYys0B7qWN7cL++DWZGdjqsW/maqE4ZZw9awb41JGbM82zT1Vd/5RtqZc8vYXBjUuUwC+vOo3xJ5Sy7FPrzuzIOntCaZwdNqKmszQfC/s8QKzc3yq2JjvlLyVKf7ClsYTPEHmDpbaCCLODwrJYjaJti73vR6+0SqOR6i2MNBxAzsO/zbLOkLmvBQJ1DZosBFizJqM/t8f/mKxPlZRcNOSD9AoN6LeQ4CP8p/F+BQgs6F4drRJqWeU1IXvrEhflAr8U+lE0SqSj2vD7rri3Qqmi8=
        file: artifacts/*AppImage
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
      deploy:
        provider: releases
        api_key:
          secure: HZQ/M926XJHnhjA+r9PbLtgSE8ZYsxJ7oEA/6xxBZiK5WpCsFSYV3m2Sd1UGtkiFa6eawdwdI+0U2P0UBe/B1S17Y2euR/kGLbUa6C6PDiMlRLxVQLGWAIpYh8/k+8KA0ZcQbTv9gOkVfsz/ZFNZZRuwFKTVwPDXxORjX43ghVOSpfaOSqxFbDOtn+q1ywLF385j9mzy65KS1BcZCz96atpuJzcl7gDFT0PNrXbPIHqj46HXQbpb17/0hkZ3XwR9Q2cp577RmrJfOxw0Ac9CQrLE7Y9Qz8y4qOd42f1WR3T14PwfJl9MzEc14SHgpTxDf4LsHZSKtcAOdKoQ9p4c6InQO29C/23tEVeiw/c+BQeL71HCJ/BbQUn3WbRgWMj1TagJRV8iZpV6+D+VTbwVJYys0B7qWN7cL++DWZGdjqsW/maqE4ZZw9awb41JGbM82zT1Vd/5RtqZc8vYXBjUuUwC+vOo3xJ5Sy7FPrzuzIOntCaZwdNqKmszQfC/s8QKzc3yq2JjvlLyVKf7ClsYTPEHmDpbaCCLODwrJYjaJti73vR6+0SqOR6i2MNBxAzsO/zbLOkLmvBQJ1DZosBFizJqM/t8f/mKxPlZRcNOSD9AoN6LeQ4CP8p/F+BQgs6F4drRJqWeU1IXvrEhflAr8U+lE0SqSj2vD7rri3Qqmi8=
        file: artifacts/*dmg
