# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Secrets
secure: "MZ83siFb+bUNzCUKpwU4IQw2lmvewUP2viEzvmdfrD5MTsGjphfZxTaAbnHSrDt+2KmPnRi/HP4V9jN+RyWLrE1aKhVsuIVReDk8erWa42baafiDZwrNJac+0BP8shQ0cAtSzSA1LAWCVovaCoAU/WfAMEN8N6IpZ1eTqpL7/rBeVQZk38t0mwxGNmHUoFwkFRLrq8bvTbSk/XO2Mw6vrgEpr1cqZvKg6S/4maJEO6rkY2JFDC1eK4BnqgmwWO/8fe6VYAuLL4a/7VH4Jno/q23vdRad4pK/5N/4wyhoB+G/5uAW1PJF/tC2QY11NkFuhTjW/ddXqlrpxi57ev3GDoA4qEFVYWK022N+X0oo2sS7kIs67mgWJiAmw7O3WOugiFOkpz9RB/n4eWGg+i8kKDqNEgWGb1xRTAhUmEuHXO747RMNeZuaQJEqprS9eSBnRFByx01YUhCNd7HW89nsM7V3J/RE9IBsN+lbDPIM1B+flp6pYLRtcTNPCkukzVzTqkviLw1VVKi9XSkixKGL01PflXkteEgcSCXGvr1sExyPv4N1DSg3P+MV7nu8v8kpxKVuqkWhJYO4na4AO2r7o5x8jv7rMkOvBp+yyVaWIyioTthA61fs1WRCZj5jbLFWO6bZ78X5uGuaM2hiBg75usEs6k7DWPuUDwqgPfVu9jk="

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
      before_deploy: ./ci/prep_deploy
      deploy:
        provider: releases
        skip_cleanup: true
        name: 22
        body: "Continuous build ${TRAVIS_TAG} ${RELEASE_NAME}"
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: artifacts/*AppImage
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
      before_deploy: ./ci/prep_deploy
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: "${GITHUB_TOKEN}"
        file: artifacts/*dmg

# Branch Safelist (allow only master and version-tagged branches)
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
