# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
      before_deploy:
        - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis-deploy -O travis-deploy
        - chmod u+x ./travis-deploy
      deploy:
        provider: script
        skip_cleanup: true
        on:
          all_branches: true
        script: ./travis-deploy -n "Release ${TRAVIS_TAG}" -f Recent.md -w artifacts/*AppImage
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
      before_deploy:
        - wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/travis-deploy -O travis-deploy
        - chmod u+x ./travis-deploy
      deploy:
        provider: script
        skip_cleanup: true
        on:
          all_branches: true
        script: ./travis-deploy -n "Release ${TRAVIS_TAG}" -f Recent.md -w artifacts/*dmg

# Branch Safelist (allow only develop and version-tagged branches)
branches:
  only:
    - develop
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
