# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - bison
      - create-dmg

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build
      cache:
        directories:
          - artifacts
    - stage: Build
      name: OSX
      os: osx
      cache:
        directories:
          - artifacts
      script: ./ci/osx.highsierra/osx.build
